# permissions for end users to view policybindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: policybinding-viewer-role
rules:
- apiGroups:
  - minio.min.io.min.io
  resources:
  - policybindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - minio.min.io.min.io
  resources:
  - policybindings/status
  verbs:
  - get
